### ISSUE TITLE
Feature: Add paper links to research body and research intro page

### ISSUE THREAD

**Issue by thinkjrs** [thinkjrs/lottamob#10]
Let's have direct links to article content (files) on the introductory page site and the on the link article themselves.

**Comment by Lottamob** [comment]
Sounds good!

**Comment by Lottamob** [comment]
As I post things now, I fill in the titles just to create the slugs, assuming the titles will now be displayed. How are slugs created without titles? Shall we keep them and just not display them?

Where do I upload Pdfs?

**Comment by Lottamob** [comment]
I now have three articles saved. Let us see how the setup works. Before I create more, I would like to check with you:
1. Does it make sense as I do now to use a blue pallet in different shades? I am just using a powerpoint default now and it is not pretty.
2. How do my articles get published? Now I can see no results from publishing?
3. Where to put my pdf uploads. 
THANK YOU!!

**Comment by thinkjrs** [comment]
Closed this because the links are now internal to each page + auto populate within the /research, /articles, and /blog endpoints.
